---
- name: Backup config volume
  include_role:
    name: my_docker
    tasks_from: backup_volumes
  vars:
    volume_names:
      - deluge-config
    container_name: deluge
    image_name: lscr.io/linuxserver/deluge