---
- name: Configure Deluge container
  docker_container:
    name: deluge
    image: lscr.io/linuxserver/deluge
    restart_policy: unless-stopped
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: "{{ timezone }}"
      DELUGE_LOGLEVEL: 'error'
    volumes:
      - 'deluge-config:/config'
      - '{{ data_path }}/media/downloads:/downloads'
    ports:
      - '8112:8112'
      - '6881:6881'
      - '6881:6881/udp'
