---
- name: Configure Deluge container
  docker_container:
    name: deluge
    image: lscr.io/linuxserver/deluge
    pull: "{{ update_images }}"
    restart_policy: unless-stopped
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: "{{ timezone }}"
      DELUGE_LOGLEVEL: 'error'
    volumes:
      - 'deluge-config:/config'
      - '{{ downloads_path }}:/downloads'
    ports:
      - '6881:6881'
      - '6881:6881/udp'
    expose:
      - '8112'
    networks:
      - name: caddy
