---
- name: Configure Nextcloud AIO container
  docker_container:
    name: nextcloud-aio-mastercontainer
    image: nextcloud/all-in-one:latest
    init: true
    pull: "{{ update_images }}"
    restart_policy: always
    env:
      APACHE_PORT: '11000'
      APACHE_IP_BINDING: '0.0.0.0'
      BORG_RETENTION_POLICY: '--keep-within=7d --keep-weekly=4 --keep-monthly=6'
      NEXTCLOUD_DATADIR: '/data/files'
    volumes:
      - 'nextcloud_aio_mastercontainer:/mnt/docker-aio-config'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    ports:
      - '501:8080'
    networks:
      - name: caddy
