---
- name: Configure Mealie container
  docker_container:
    name: mealie
    image: ghcr.io/mealie-recipes/mealie:nightly
    restart_policy: unless-stopped
    memory: 1000M
    env:
      ALLOW_SIGNUP: 'true'
      PUID: '1000'
      PGID: '1000'
      TZ: "{{ timezone }}"
      MAX_WORKERS: '1'
      WEB_CONCURRENCY: '1'
      BASE_URL: "https://mealie.{{ public_url }}"
    volumes:
      - 'mealie-data:/app/data'
    ports:
      - '9925:9000'
