---
- name: Configure Jellyfin container
  docker_container:
    name: jellyfin
    image: lscr.io/linuxserver/jellyfin
    pull: "{{ update_images }}"
    restart_policy: unless-stopped
    devices:
      - '/dev/dri:/dev/dri'
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: "{{ timezone }}"
    volumes:
      - 'jellyfin-config:/config'
      - '{{ shows_path }}:/data/shows'
      - '{{ movies_path }}:/data/movies'
    expose:
      - '8096'
    networks:
      - name: caddy
