---
- name: Configure Jellyfin container
  docker_container:
    name: jellyfin
    image: lscr.io/linuxserver/jellyfin
    restart_policy: unless-stopped
    devices:
      - '/dev/dri:/dev/dri'
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: "{{ timezone }}"
    volumes:
      - 'jellyfin-config:/config'
      - '{{ shows_path }}:/data/shows'
      - '{{ movies_path }}:/data/movies'
    ports:
      - '8096:8096'
