---
- name: Remove existing container
  include_role:
    name: container
    tasks_from: update
  vars:
    container_name: jellyfin
    image_name: lscr.io/linuxserver/jellyfin

- name: Set up the updated container
  include_tasks: main.yml
