---
- name: Remove existing container
  include_role:
    name: my_docker
    tasks_from: update_container
  vars:
    container_name: jellyfin
    image_name: lscr.io/linuxserver/jellyfin

- name: Set up the updated container
  include_tasks: main.yml
