- name: Configure Home Server
  hosts: homeserver
  become: true

  vars_files:
    - secret.yml

  vars:
    data_path: /data

  tasks:

    - name: Ensure Data Drive is mounted
      mount:
        src: /dev/sdb1
        path: "{{ data_path }}"
        fstype: ntfs
        state: mounted
        opts: permissions

    - name: Configure WG-Easy
      include_role:
        name: wg-easy

    - name: Configure DDClient
      include_role:
        name: ddclient
        apply:
          tags: testing
      tags: testing

    - name: Configure MkDocs
      include_role:
        name: mkdocs

    - name: Configure DockProm
      include_role:
        name: dockprom

    - name: Configure Homer
      include_role:
        name: homer

    - name: Configure Calibre
      include_role:
        name: calibre

    - name: Configure Jellyfin
      include_role:
        name: jellyfin

    - name: Configure Nextcloud
      include_role:
        name: nextcloud

    - name: Configure Home Assistant
      include_role:
        name: homeassistant

    - name: Configure FreshRSS
      include_role:
        name: freshrss

    - name: Configure Deluge
      include_role:
        name: deluge

    - name: Configure Radarr
      include_role:
        name: radarr

    - name: Configure Sonarr
      include_role:
        name: sonarr

    - name: Configure Overleaf
      include_role:
        name: overleaf
