- name: Configure Home Pi
  hosts: homepi
  become: true

  vars_files:
    - secret.yml

  tasks:

    - name: Configure PiHole
      include_role:
        name: pihole

    - name: Uptime Kuma
      include_role:
        name: uptime-kuma
