- name: Configure Home Server
  hosts: homeserver
  become: true

  vars_files:
    - secret.yml

  vars:
    data_path: /data

  tasks:

    - name: Ensure Data Drive is mounted
      mount:
        src: "UUID={{ data_uuid }}"
        path: "{{ data_path }}"
        fstype: ext4
        state: mounted

    - name: Configure WG-Easy
      include_role:
        name: wg-easy
        apply:
          tags: wireguard
      tags: wireguard

    - name: Configure DDClient
      include_role:
        name: ddclient

    - name: Configure Nginx Proxy Manager
      include_role:
        name: nginx-proxy-manager
        apply:
          tags: nginx
      tags: nginx

    - name: Configure MkDocs
      include_role:
        name: mkdocs
        apply:
          tags: docs
      tags: docs

    - name: Configure DockProm
      include_role:
        name: dockprom

    - name: Configure Scrutiny
      include_role:
        name: scrutiny
        apply:
          tags: scrutiny
      tags: scrutiny

    - name: Configure Homer
      include_role:
        name: homer
        apply:
          tags: homer
      tags: homer

    - name: Uptime Kuma
      include_role:
        name: uptime-kuma

    - name: Configure Calibre
      include_role:
        name: calibre

    - name: Configure Jellyfin
      include_role:
        name: jellyfin

    - name: Configure Nextcloud
      include_role:
        name: nextcloud

    - name: Configure Home Assistant
      include_role:
        name: homeassistant

    - name: Configure FreshRSS
      include_role:
        name: freshrss

    - name: Configure Deluge
      include_role:
        name: deluge

    - name: Configure Radarr
      include_role:
        name: radarr
        apply:
          tags: arr
      tags: arr

    - name: Configure Sonarr
      include_role:
        name: sonarr
        apply:
          tags: arr
      tags: arr

    - name: Configure Bazarr
      include_role:
        name: bazarr
        apply:
          tags: arr
      tags: arr

    - name: Configure Overleaf
      include_role:
        name: overleaf
