- name: Configure Home Pi
  hosts: homepi
  become: true

  vars_files:
    - secret.yml

  tasks:

    - name: Configure WG-Easy
      include_role:
        name: wg-easy

    - name: Configure PiHole
      include_role:
        name: pihole
