- name: Configure Home Server
  hosts: homeserver
  become: true

  tasks:

    - name: Ensure Data Drive is mounted
      mount:
        src: "UUID={{ data_uuid }}"
        path: "{{ data_path }}"
        fstype: ext4
        state: mounted

    - name: Configure Homer dashboard
      include_role:
        name: homer
        apply:
          tags: homer
      tags: homer

    - name: Configure Mkdocs documentation
      include_role:
        name: mkdocs
        apply:
          tags: docs
      tags: docs

    - name: Configure Administration services
      block:
        - name: Configure ZeroTier
          include_role:
            name: zerotier

        - name: Configure Caddy
          include_role:
            name: caddy
            apply:
              tags: caddy
          tags: caddy

        - name: Configure DockProm
          include_role:
            name: dockprom

        - name: Configure Scrutiny
          include_role:
            name: scrutiny

        - name: Uptime Kuma
          include_role:
            name: uptime-kuma
      tags: admin

    - name: Configure Media managment services
      block:
        - name: Configure Syncthing
          include_role:
            name: syncthing

        - name: Configure Deluge
          include_role:
            name: deluge

        - name: Configure Sonarr
          include_role:
            name: sonarr
            apply:
              tags: arr
          tags: arr
          
        - name: Configure Radarr
          include_role:
            name: radarr
            apply:
              tags: arr
          tags: arr

        - name: Configure Readarr
          include_role:
            name: readarr
            apply:
              tags: arr
          tags: arr

        - name: Configure Bazarr
          include_role:
            name: bazarr
            apply:
              tags: arr
          tags: arr

        - name: Configure Prowlarr
          include_role:
            name: prowlarr
            apply:
              tags: arr
          tags: arr
      tags: media

    - name: Configure Application services
      block:
        - name: Configure Nextcloud
          include_role:
            name: nextcloud

        - name: Configure Jellyfin
          include_role:
            name: jellyfin

        - name: Configure Calibre
          include_role:
            name: calibre

        - name: Configure Home Assistant
          include_role:
            name: homeassistant

        - name: Configure Mealie
          include_role:
            name: mealie

        - name: Configure PufferPanel
          include_role:
            name: pufferpanel

        - name: Configure Paperless
          include_role:
            name: paperless-ngx

        - name: Configure Gitea
          include_role:
            name: gitea
      tags: app
