---
- name: Basic configuration for all hosts
  hosts: all
  become: true
  
  vars:
      pip_install_packages:
        - name: docker
        - name: docker-compose

  roles:
    - geerlingguy.pip
    - geerlingguy.docker
    - ssh

  tasks:

    - name: Apply laptop configuration
      include_role:
        name: laptop
      when: is_laptop | default(false)

- import_playbook: homeserver.yml
- import_playbook: torreserver.yml
