---
- name: Basic configuration for all hosts
  hosts: all
  become: true
  
  vars:
      pip_install_packages:
        - name: docker
        - name: docker-compose

  roles:
    - geerlingguy.pip
    - geerlingguy.docker

- import_playbook: homepi.yml
- import_playbook: server.yml
