---
- name: Basic configuration for all hosts
  hosts: all
  become: true

  vars_files:
    - secret.yml
  
  vars:
      pip_install_packages:
        - name: docker
        - name: docker-compose

  roles:
    - geerlingguy.pip
    - geerlingguy.docker
    - ssh

# - import_playbook: homepi.yml
- import_playbook: homeserver.yml
- import_playbook: torreserver.yml
