- name: Configure Home Server
  hosts: server
  become: true

  vars_files:
    - secret.yml

  tasks:

    - name: Ensure Data Drive is mounted
      mount:
        src: /dev/sdb1
        path: "{{ data_path }}"
        fstype: ntfs
        state: mounted
        opts: permissions

    - name: Configure Homer
      include_role:
        name: homer

    - name: Configure Calibre
      include_role:
        name: calibre

    - name: Configure Jellyfin
      include_role:
        name: jellyfin

    - name: Configure Nextcloud
      include_role:
        name: nextcloud

    - name: Configure Home Assistant
      include_role:
        name: homeassistant
