- name: Configure Home Server
  hosts: server
  become: true

  vars_files:
    - secret.yml

  tasks:

    - name: Configure Homer
      include_role:
        name: homer

    - name: Configure Calibre
      include_role:
        name: calibre

    - name: Configure Jellyfin
      include_role:
        name: jellyfin

    - name: Configure Seafile
      include_role:
        name: seafile
