---
- name: Configure WG Easy Container
  docker_container:
    name: wg-easy
    image: weejewel/wg-easy
    state: started
    restart_policy: unless-stopped
    capabilities:
      - NET_ADMIN
      - SYS_MODULE
    env:
      WG_HOST: "{{ ddns_endpoint }}"
      PASSWORD: "{{ wg_easy_password }}"
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv4.ip_forward: 1
    volumes:
      - "wg-easy:/etc/wireguard"
