---
- name: Backup config volume
  include_role:
    name: my_docker
    tasks_from: backup_volumes
  vars:
    volume_names:
      - jellyseerr-config
    container_name: jellyseerr
    image_name: fallenbagel/jellyseerr