---
- name: Backup sharelatex volume
  include_role:
    name: my_docker
    tasks_from: backup_volumes
  vars:
    volume_names:
      - overleaf_sharelatex-data
    container_name: overleaf_sharelatex
    image_name: sharelatex/sharelatex

- name: Backup mongo volume
  include_role:
    name: my_docker
    tasks_from: backup_volumes
  vars:
    volume_names:
      - overleaf_mongo-data
    container_name: overleaf_mongo
    image_name: mongo:4.4

- name: Backup redis volume
  include_role:
    name: my_docker
    tasks_from: backup_volumes
  vars:
    volume_names:
      - overleaf_redis-data
    container_name: overleaf_redis
    image_name: redis:5
