---
# UNUSED! This service is no longer used, so it may not work

# Based on the docker compose file by Overleaf
# https://github.com/overleaf/overleaf/blob/main/docker-compose.yml
- name: Configure Overleaf container
  docker_compose:
    project_name: overleaf
    definition:
      version: '2'
      volumes:
        sharelatex-data:
        mongo-data:
        redis-data:
      services:
        sharelatex:
          container_name: sharelatex
          image: sharelatex/sharelatex
          restart: always
          depends_on:
            mongo:
                condition: service_healthy
            redis:
                condition: service_started
          ports:
            - 4555:80
          links:
            - mongo
            - redis
          volumes:
          - sharelatex-data:/var/lib/sharelatex
          environment:
            - SHARELATEX_APP_NAME=Overleaf Canales Edition
            - SHARELATEX_MONGO_URL=mongodb://mongo/sharelatex
            - SHARELATEX_REDIS_HOST=redis
            - REDIS_HOST=redis
            - ENABLED_LINKED_FILE_TYPES='project_file,project_output_file'
            - ENABLE_CONVERSIONS='true'
            - EMAIL_CONFIRMATION_DISABLED='true'
            - TEXMFVAR=/var/lib/sharelatex/tmp/texmf-var
            - "SHARELATEX_SITE_URL=http://{{ ansible_host }}:4555"
            - "SHARELATEX_NAV_TITLE=Canales ShareLaTeX Instance"
            - "SHARELATEX_ADMIN_EMAIL=albertcanalesros@gmail.com"
            
            - "SHARELATEX_EMAIL_FROM_ADDRESS={{ mail_user }}"
            - SHARELATEX_EMAIL_SMTP_HOST=smtp.gmail.com
            - SHARELATEX_EMAIL_SMTP_PORT='587'
            - SHARELATEX_EMAIL_SMTP_SECURE="false"
            - "SHARELATEX_EMAIL_SMTP_USER={{ mail_user }}"
            - "SHARELATEX_EMAIL_SMTP_PASS={{ mail_pass }}"
            - SHARELATEX_EMAIL_SMTP_TLS_REJECT_UNAUTH="false"
            - SHARELATEX_EMAIL_SMTP_IGNORE_TLS="false"
            - SHARELATEX_EMAIL_SMTP_NAME='Canales Server'
            - SHARELATEX_EMAIL_SMTP_LOGGER=true
            - SHARELATEX_CUSTOM_EMAIL_FOOTER='This is an automatic message'

        mongo:
          container_name: mongo
          image: mongo:4.4
          restart: always
          expose:
            - 27017
          volumes:
            - mongo-data:/data/db
          healthcheck:
            test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
            interval: 10s
            timeout: 10s
            retries: 5

        redis:
          container_name: redis
          image: redis:5
          restart: always
          expose:
            - 6379
          volumes:
            - redis-data:/data
