---
# Based on the official documentation:
# https://docs.nextcloud.com/server/latest/admin_manual/maintenance/backup.html

- name: Enable Maintenance mode
  community.docker.docker_container_exec:
    container: nextcloud-app
    command: php occ maintenance:mode --on
    # chdir: /var/www/html/nextcloud/
    user: www-data
  register: result

# Should be done with mysqldump, but this is enough for now
- name: Backup database volume
  include_role:
    name: my_docker
    tasks_from: backup_volumes
  vars:
    volume_names:
      - nextcloud_nextcloud-db
    container_name: nextcloud-db
    image_name: mariadb:10.5

- name: Backup data volume
  include_role:
    name: my_docker
    tasks_from: backup_volumes
  vars:
    volume_names:
      - nextcloud_nextcloud-nextcloud
    container_name: nextcloud_nextcloud-app
    image_name: nextcloud

- name: Disable Maintenance mode
  community.docker.docker_container_exec:
    container: nextcloud-app
    command: php occ maintenance:mode --off
    # chdir: /var/www/html/nextcloud/
    user: www-data
  register: result