---
- name: Avoid suspension when closing lid
  lineinfile:
    dest: /etc/systemd/logind.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^#?HandleLidSwitch="
      line: "HandleLidSwitch=ignore"
    - regexp: "^#?HandleLidSwitchExternalPower="
      line: "HandleLidSwitchExternalPower=ignore"
    - regexp: "^#?HandleLidSwitchDocked="
      line: "HandleLidSwitchDocked=ignore"
    - regexp: "^#?LidSwitchIgnoreInhibited="
      line: "LidSwitchIgnoreInhibited=no"
  notify: restart-logind
