---
- name: Configure Gitea container
  docker_container:
    name: gitea
    image: gitea/gitea
    restart_policy: always
    env:
      USER_UID: '1000'
      USER_GID: '1000'
      DISABLE_REGISTRATION: 'true'
    volumes:
      - 'gitea-data:/data'
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - '3333:3000'
      - '222:22'
