---
- name: Backup data volume
  include_role:
    name: my_docker
    tasks_from: backup_volumes
  vars:
    volume_names:
      - zerotier-data
    container_name: zerotier
    image_name: zyclonite/zerotier
