---
- name: Configure FreshRSS container
  docker_container:
    name: freshrss
    image: lscr.io/linuxserver/freshrss
    restart_policy: unless-stopped
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: "{{ timezone }}"
    volumes:
      - 'freshrss-config:/config'
      - '{{ data_path }}/media/shows:/data/shows'
      - '{{ data_path }}/media/movies:/data/movies'
    ports:
      - '4000:80'
