---
# Further configuration based this post:
# https://yams.media/config/prowlarr/

- name: Configure Prowlarr container
  docker_container:
    name: prowlarr
    image: lscr.io/linuxserver/prowlarr
    pull: "{{ update_images }}"
    restart_policy: unless-stopped
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: "{{ timezone }}"
    volumes:
      - 'prowlarr-config:/config'
    expose:
      - '9696'
    networks:
      - name: caddy
