---
- name: Configure Homer container
  docker_container:
    name: homer
    image: b4bz/homer
    restart_policy: always
    ports:
      - '8080:8080'
    volumes:
      - 'homer-assets:/www/assets'

- name: Get homer volume info
  docker_volume_info:
    name: homer-assets
  register: homer_volume

# The icons are copied in two steps because the
# copy module is really slow on local -> remote

- name: Copy icons into home directory
  synchronize:
    src: icons/
    dest: "/home/{{ ansible_user }}/homer-icons/"
  become: false

- name: Copy icons into assets directory
  copy:
    src: "/home/{{ ansible_user }}/homer-icons/"
    dest: "{{ homer_volume.volume.Mountpoint }}/icons"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    remote_src: true

- name: Copy config template to assets
  template:
    src: config.yml.j2
    dest: "{{ homer_volume.volume.Mountpoint }}/config.yml"
