---
- name: Configure Sonarr container
  docker_container:
    name: sonarr
    image: lscr.io/linuxserver/sonarr
    pull: "{{ update_images }}"
    restart_policy: unless-stopped
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: "{{ timezone }}"
    volumes:
      - 'sonarr-config:/config'
      - '{{ shows_path }}:/tv'
      - '{{ downloads_path }}:/downloads'
    expose:
      - '8989'
    networks:
      - name: caddy
