---
- name: Configure Bazarr container
  docker_container:
    name: bazarr
    image: lscr.io/linuxserver/bazarr
    restart_policy: unless-stopped
    env:
      PUID: '1000'
      PGID: '1000'
      TZ: "{{ timezone }}"
    volumes:
      - 'bazarr-config:/config'
      - '{{ data_path }}/media/shows:/tv'
      - '{{ data_path }}/media/movies:/movies'
    ports:
      - '6767:6767'
