---
- name: "Stop the container {{ container_name }}"
  docker_container:
    name: "{{ container_name }}"
    image: "{{ image_name }}"
    state: stopped
  when: container_name is defined and image_name is defined and container_start_stop

- name: "Backup each volume of container {{ container_name }}"
  include_tasks: backup_volumes_each.yml
  loop: "{{ volume_names }}"
  loop_control:
    loop_var: volume_name

- name: "Start the container {{ container_name }}"
  docker_container:
    name: "{{ container_name }}"
    state: started
  when: container_name is defined and container_start_stop
