---
- name: Configure PufferPanel container
  docker_container:
    name: pufferpanel
    image: pufferpanel/pufferpanel
    pull: "{{ update_images }}"
    restart_policy: on-failure
    expose:
      - '8080'
      - '5657'        # SFTP
      - '10000-10100' # Game Ports
    networks:
      - name: caddy
    volumes:
      - 'pufferpanel-config:/etc/pufferpanel'
      - 'pufferpanel-data:/var/lib/pufferpanel'
      - '/var/run/docker.sock:/var/run/docker.sock'
