---
- name: Configure Uptime Kuma Container
  docker_container:
    name: uptime-kuma
    image: louislam/uptime-kuma
    pull: "{{ update_images }}"
    state: started
    restart_policy: always
    expose:
      - '3001'
    networks:
      - name: caddy
    volumes:
      - 'uptime-kuma:/app/data'
