---
- name: Configure Uptime Kuma Container
  docker_container:
    name: uptime-kuma
    image: louislam/uptime-kuma
    pull: "{{ update_images }}"
    state: started
    restart_policy: always
    ports:
      - '3001:3001'
    volumes:
      - 'uptime-kuma:/app/data'
