---
- name: Configure Home Assistant container
  docker_container:
    name: homeassistant
    image: homeassistant/home-assistant
    pull: "{{ update_images }}"
    state: started
    restart_policy: unless-stopped
    network_mode: host
    privileged: true
    env:
      TZ: "{{ timezone }}"
    volumes:
      - 'homeassistant-config:/config'
      - '{{ books_path }}:/books'
