---
- name: Remove existing containers
  include_role:
    name: my_docker
    tasks_from: update_container
  vars:
    container_name: homeassistant
    image_name: homeassistant/home-assistant

- name: Set up the updated container
  include_tasks: main.yml
