---
- name: Backup config volume
  include_role:
    name: my_docker
    tasks_from: backup_volumes
  vars:
    volume_names:
      - syncthing-config
    container_name: syncthing
    image_name: lscr.io/linuxserver/syncthing
