---
- name: Backup dockprom volume
  include_role:
    name: my_docker
    tasks_from: backup_volumes
  vars:
    volume_names:
      - dockprom

- name: Backup prometheus volume
  include_role:
    name: my_docker
    tasks_from: backup_volumes
  vars:
    volume_names:
      - dockprom_prometheus-data
    container_name: dockprom_prometheus
    image_name: prom/prometheus:v2.37.0

- name: Backup grafana volume
  include_role:
    name: my_docker
    tasks_from: backup_volumes
  vars:
    volume_names:
      - dockprom_grafana-data
    container_name: dockprom_grafana
    image_name: grafana/grafana:9.0.5
