---

- name: Pull the documentation repository
  git:
    repo: "https://oauth2:{{ github_fine_token }}@github.com/{{ repo_owner }}/{{ repo_name }}.git"
    dest: "{{ docs_path }}"
  register: docs_repo
  when: false

- name: Configure MkDocs container
  docker_container:
    name: mkdocs
    image: polinux/mkdocs
    restart_policy: always
    restart: "{{ docs_repo.changed }}"
    env:
      ADD_MODULES: 'fontawesome-markdown mkdocs-git-revision-date-localized-plugin mkdocs-material'
      FAST_MODE: 'true'
      DOCS_DIRECTORY: '/mkdocs'
    ports:
      - '8000:8000'
    volumes:
      - '{{ docs_path }}:/mkdocs'
