---
- name: Run ssh role if not done already
  include_role:
    name: ssh
  when: ssh_role_ran is not defined

- name: Add the deploy key to the Github repository
  github_deploy_key:
    key: "{{ ssh_keypair.public_key }}"
    name: homeserver
    owner: "{{ repo_owner }}"
    repo: "{{ repo_name }}"
    token: "{{ github_deploy_token }}"

- name: Pull the documentation repository
  git:
    repo: "git@github.com:{{ repo_owner }}/{{ repo_name }}.git"
    dest: "{{ data_path }}/docs"
    key_file: "{{ ssh_keypair.filename }}"
    accept_hostkey: true

- name: Configure MkDocs container
  docker_container:
    name: mkdocs
    image: polinux/mkdocs
    restart_policy: always
    env:
      ADD_MODULES: 'fontawesome-markdown mkdocs-git-revision-date-localized-plugin mkdocs-material'
      FAST_MODE: 'true'
      DOCS_DIRECTORY: '/mkdocs'
    ports:
      - '8000:8000'
    volumes:
      - '{{ data_path }}/docs:/mkdocs'
